# Generated by Django 5.2 on 2025-05-20 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tareafragmentada',
            name='fecha_planificada_fin_original',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='fecha_planificada_inicio_original',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='motivo_modificacion',
            field=models.CharField(blank=True, choices=[('BASE', 'Planificación Base'), ('AJUSTE_DIA', 'Ajuste por Fin de Día'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('CONFLICTO_MAQUINA', 'Ajuste por Conflicto de Máquina'), ('CONTINUACION', 'Continuación de Tarea')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='version_planificacion',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='HistorialPlanificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reajuste', models.DateTimeField(auto_now_add=True)),
                ('fecha_referencia', models.DateField()),
                ('tipo_reajuste', models.CharField(choices=[('INICIAL', 'Planificación Inicial'), ('DIARIO', 'Reajuste Diario'), ('MANUAL', 'Reajuste Manual')], max_length=20)),
                ('estado_anterior', models.JSONField()),
                ('estado_posterior', models.JSONField()),
                ('resumen_dia', models.JSONField(blank=True, null=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.programaproduccion')),
            ],
            options={
                'ordering': ['-fecha_reajuste'],
            },
        ),
    ]
