# Generated by Django 5.2 on 2025-05-21 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0003_tareafragmentada_fecha_planificada_fin_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialplanificacion',
            name='estado_anterior',
        ),
        migrations.RemoveField(
            model_name='historialplanificacion',
            name='estado_posterior',
        ),
        migrations.RemoveField(
            model_name='historialplanificacion',
            name='resumen_dia',
        ),
        migrations.AddField(
            model_name='historialplanificacion',
            name='reporte_diario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobManagement.reportediarioprograma'),
        ),
        migrations.AddField(
            model_name='historialplanificacion',
            name='resumen_cambios',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='historialplanificacion',
            name='tareas_modificadas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='historialplanificacion',
            name='timeline_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='historialplanificacion',
            index=models.Index(fields=['programa', 'fecha_referencia'], name='JobManageme_program_cde2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='historialplanificacion',
            index=models.Index(fields=['fecha_reajuste'], name='JobManageme_fecha_r_775fb4_idx'),
        ),
    ]
