# Generated by Django 5.2 on 2025-05-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0004_remove_historialplanificacion_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialplanificacion',
            name='timeline_actualizada',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='historialplanificacion',
            name='timeline_original',
            field=models.JSONField(default=dict),
        ),
    ]
