# Generated by Django 5.2 on 2025-05-30 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0005_historialplanificacion_timeline_actualizada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialplanificacion',
            name='resumen_cambios',
        ),
        migrations.AddField(
            model_name='historialplanificacion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialplanificacion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='cantidad_total_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad original asignada a la tarea', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='continuaciones_futuras',
            field=models.ManyToManyField(related_name='tareas_anteriores', to='JobManagement.tareafragmentada'),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='estado_validacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Validación'), ('VALIDADO', 'Validado'), ('ERROR', 'Error en Validación')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='historial_cambios',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='ultima_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialplanificacion',
            name='tipo_reajuste',
            field=models.CharField(choices=[('INICIAL', 'Planificación Inicial'), ('DIARIO', 'Reajuste Diario'), ('MANUAL', 'Reajuste Manual'), ('CONTINUACION', 'Continuación de Tareas'), ('AJUSTE_AUTOMATICO', 'Ajuste Automático')], max_length=20),
        ),
    ]
