# Generated by Django 5.2 on 2025-06-12 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0006_remove_historialplanificacion_resumen_cambios_and_more'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstandarMaquinaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estandar', models.IntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina')),
                ('pieza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estandares_maquina', to='Product.pieza')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.proceso')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estandares_maquina', to='Product.producto')),
            ],
            options={
                'constraints': [models.CheckConstraint(check=models.Q(('producto__isnull', False), ('pieza__isnull', False), _connector='OR'), name='producto_or_pieza_required')],
                'unique_together': {('pieza', 'proceso', 'maquina'), ('producto', 'proceso', 'maquina')},
            },
        ),
    ]
