# Generated by Django 5.2 on 2025-06-26 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0007_estandarmaquinaproceso'),
        ('Operator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionExperimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('estrategia', models.CharField(choices=[('CONTINUA', 'Ventanas Continuas'), ('HIBRIDA', 'Híbrida (Continua + Puntos Control)'), ('INTELIGENTE', 'Inteligente con IA')], default='CONTINUA', max_length=20)),
                ('considera_disponibilidad_operadores', models.BooleanField(default=True)),
                ('considera_disponibilidad_maquinas', models.BooleanField(default=True)),
                ('permite_solapamiento_procesos', models.BooleanField(default=False)),
                ('margen_seguridad_horas', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('reajuste_automatico', models.BooleanField(default=False)),
                ('umbral_reajuste_porcentaje', models.DecimalField(decimal_places=2, default=20.0, help_text='% de desvío que dispara reajuste automático', max_digits=5)),
                ('hora_inicio_laboral', models.TimeField(default='07:45')),
                ('hora_fin_laboral', models.TimeField(default='17:45')),
                ('considera_fines_semana', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parametros_avanzados', models.JSONField(default=dict, help_text='Parámetros adicionales en formato JSON')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración Experimental',
                'verbose_name_plural': 'Configuraciones Experimentales',
                'db_table': 'experimental_configuracion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SesionExperimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('datos_sistema_actual', models.JSONField(default=dict, help_text='Snapshot del sistema actual para comparar')),
                ('metricas_resultado', models.JSONField(default=dict, help_text='Métricas finales de la sesión')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JobManagement.configuracionexperimental')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_experminetales', to='JobManagement.programaproduccion')),
            ],
            options={
                'verbose_name': 'Sesión Experimentales',
                'verbose_name_plural': 'Sesiones Experimentales',
                'db_table': 'experimental_sesion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='VentanaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_completada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_inicio_estimada', models.DateTimeField()),
                ('fecha_fin_estimada', models.DateTimeField()),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_CURSO', 'En Curso'), ('COMPLETADO', 'Completado'), ('SUSPENDIDO', 'Suspendido'), ('REPLANIFICADO', 'Replanificado')], default='PLANIFICADO', max_length=20)),
                ('version_planificacion', models.IntegerField(default=1)),
                ('requiere_reajuste', models.BooleanField(default=False)),
                ('tiempo_estimado_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('velocidad_planificada', models.DecimalField(blank=True, decimal_places=2, help_text='Unidades por hora planificadas', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('maquina_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobManagement.maquina')),
                ('operador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operator.operador')),
                ('proceso_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventanas_experimentales', to='JobManagement.itemruta')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventanas_trabajo', to='JobManagement.programaproduccion')),
            ],
            options={
                'verbose_name': 'Ventana de Trabajo',
                'verbose_name_plural': 'Ventana de Trabajo',
                'db_table': 'experimental_ventana_trabajo',
                'ordering': ['fecha_inicio_estimada'],
            },
        ),
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_completada_acumulada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_invertido', models.DurationField()),
                ('observaciones', models.TextField(blank=True)),
                ('debe_continuar', models.BooleanField(default=False)),
                ('velocidad_real', models.DecimalField(blank=True, decimal_places=2, help_text='Unidades por hora reales', max_digits=8, null=True)),
                ('hubo_problemas', models.BooleanField(default=False)),
                ('tipo_problemas', models.CharField(blank=True, max_length=200)),
                ('tiempo_perdido', models.DurationField(blank=True, null=True)),
                ('cantidad_rechazada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_calidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operator.operador')),
                ('ventana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_control', to='JobManagement.ventanatrabajo')),
            ],
            options={
                'verbose_name': 'Punto de Control',
                'verbose_name_plural': 'Puntos de Control',
                'db_table': 'experimental_punto_control',
                'ordering': ['fecha', 'ventana__fecha_inicio_estimada'],
            },
        ),
        migrations.AddIndex(
            model_name='ventanatrabajo',
            index=models.Index(fields=['programa', 'estado'], name='experimenta_program_f650e7_idx'),
        ),
        migrations.AddIndex(
            model_name='ventanatrabajo',
            index=models.Index(fields=['fecha_inicio_estimada', 'fecha_fin_estimada'], name='experimenta_fecha_i_b157cb_idx'),
        ),
        migrations.AddIndex(
            model_name='ventanatrabajo',
            index=models.Index(fields=['proceso_original', 'estado'], name='experimenta_proceso_341357_idx'),
        ),
        migrations.AddIndex(
            model_name='puntocontrol',
            index=models.Index(fields=['fecha'], name='experimenta_fecha_a1f7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='puntocontrol',
            index=models.Index(fields=['ventana', 'fecha'], name='experimenta_ventana_42a578_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='puntocontrol',
            unique_together={('ventana', 'fecha')},
        ),
    ]
