# Generated by Django 5.2 on 2025-07-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0008_configuracionexperimental_sesionexperimental_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareafragmentada',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tareafragmentada',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='bloqueo_edicion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='modo_actualizacion',
            field=models.CharField(choices=[('MANUAL', 'Actualización Manual'), ('TIEMPO_REAL', 'Tiempo Real'), ('HIBRIDO', 'Híbrido')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='permite_edicion_rapida',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='progreso_tiempo_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='ultima_actualizacion_tiempo_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='velocidad_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
