# Generated by Django 5.2 on 2025-07-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0009_alter_tareafragmentada_options_and_more'),
        ('Operator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemruta',
            name='cantidad_en_proceso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='estado_proceso',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='fecha_fin_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='fecha_inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='historial_progreso',
            field=models.JSONField(default=list, help_text='Historial de actualizaciones de progreso'),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='observaciones_progreso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='operador_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_en_proceso', to='Operator.operador'),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='permite_progreso_directo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='porcentaje_completado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='ultima_actualizacion_progreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
