# Generated by Django 5.2 on 2025-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0010_itemruta_cantidad_en_proceso_itemruta_estado_proceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemruta',
            name='permite_salto_proceso',
            field=models.BooleanField(default=False, help_text='Permite que este proceso avance independientemente del anterior'),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='porcentaje_minimo_anterior',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='% mínimo que debe completar el proceso anterior', max_digits=5),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='tipo_dependencia',
            field=models.CharField(choices=[('ESTRICTA', 'Dependencia Estricta'), ('PARCIAL', 'Dependencia Parcial'), ('INDEPENDIENTE', 'Independiente')], default='ESTRICTA', max_length=20),
        ),
    ]
