# Generated by Django 5.2 on 2025-07-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0011_itemruta_permite_salto_proceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemruta',
            name='justificacion_salto',
            field=models.TextField(blank=True, help_text='Justificación cuando se permite salto de proceso'),
        ),
    ]
