# Generated by Django 5.2 on 2025-07-10 18:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('JobManagement', '0014_remove_experimental_system_final'),
        ('Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_hora_operador_base', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio por hora de operador', max_digits=10)),
                ('costo_hora_supervisor', models.DecimalField(decimal_places=2, default=0, help_text='Costo por hora de supervisor', max_digits=10)),
                ('costo_hora_maquina_base', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio por hora de máquina (depreciación, energía, mantenimiento)', max_digits=10)),
                ('porcentaje_costos_indirectos', models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje de costos indirectos sobre costos directos', max_digits=5)),
                ('margen_beneficio_objetivo', models.DecimalField(decimal_places=2, default=20.0, help_text='Margen de beneficio objetivo en %', max_digits=5)),
                ('costo_kg_materia_prima_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio por kg de materia prima', max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_vigencia_desde', models.DateField(default=datetime.date.today)),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Costos',
                'verbose_name_plural': 'Configuraciones de Costos',
                'ordering': ['-fecha_vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_por_unidad', models.DecimalField(decimal_places=4, help_text='Precio por unidad', max_digits=12)),
                ('precio_por_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Precio por kilogramo (opcional)', max_digits=12, null=True)),
                ('fecha_vigencia_desde', models.DateField(default=datetime.date.today)),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precio de Producto',
                'verbose_name_plural': 'Precios de Productos',
                'ordering': ['-fecha_vigencia_desde'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='estandarmaquinaproceso',
            name='producto_or_pieza_required_estandar',
        ),
        migrations.AddConstraint(
            model_name='estandarmaquinaproceso',
            constraint=models.CheckConstraint(check=models.Q(('producto__isnull', False), ('pieza__isnull', False), _connector='OR'), name='producto_or_pieza_required'),
        ),
        migrations.AddField(
            model_name='configuracioncostos',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_costos_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracioncostos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.empresaot'),
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Precio específico para cliente. Si es null, es precio general', null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.cliente'),
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='pieza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='Product.pieza'),
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='Product.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracioncostos',
            unique_together={('empresa', 'fecha_vigencia_desde')},
        ),
        migrations.AddConstraint(
            model_name='precioproducto',
            constraint=models.CheckConstraint(check=models.Q(('producto__isnull', False), ('pieza__isnull', False), _connector='OR'), name='precio_producto_or_pieza_required'),
        ),
        migrations.AlterUniqueTogether(
            name='precioproducto',
            unique_together={('pieza', 'cliente', 'fecha_vigencia_desde'), ('producto', 'cliente', 'fecha_vigencia_desde')},
        ),
    ]
