# Generated by Django 4.2.23 on 2025-08-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0001_initial'),
        ('JobManagement', '0015_configuracioncostos_precioproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operator.asignacionoperador')),
            ],
        ),
    ]
