# Generated by Django 4.2.23 on 2025-08-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0016_ingresoproduccion'),
        ('Operator', '0001_initial'),
        ('Machine', '0003_fallasmaquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoproduccion',
            name='fallas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine.fallasmaquina'),
        ),
        migrations.AddField(
            model_name='ingresoproduccion',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operator.operador'),
        ),
    ]
