# Generated by Django 4.2.23 on 2025-08-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0017_ingresoproduccion_fallas_ingresoproduccion_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
