# Generated by Django 5.2.6 on 2025-09-09 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0018_ordentrabajo_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemruta',
            name='duracion_planificada_horas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duración planificada en horas', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='fecha_fin_planificada',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora planificada de fin del proceso', null=True),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='fecha_inicio_planificada',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora planificada de inicio del proceso', null=True),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='fecha_json_base',
            field=models.DateField(blank=True, help_text='Fecha del JSON base que incluye este ItemRuta', null=True),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='fecha_ultima_planificacion',
            field=models.DateTimeField(blank=True, help_text='Cuándo se calculó por última vez la planificación', null=True),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='incluido_en_json_base',
            field=models.BooleanField(default=False, help_text='Si este ItemRuta está incluido en el JSON base actual'),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='secuencia_en_ot',
            field=models.PositiveIntegerField(blank=True, help_text='Posición en la secuencia de procesos de la OT', null=True),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='timeline_items_generados',
            field=models.JSONField(default=list, help_text='Items del timeline generados para este ItemRuta'),
        ),
        migrations.CreateModel(
            name='CambioPlanificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_cambio', models.CharField(choices=[('PRIORIDAD', 'Cambio de Prioridad'), ('ESTANDAR', 'Cambio de Estándar'), ('MAQUINA', 'Cambio de Máquina'), ('OPERADOR', 'Asignación de Operador'), ('NUEVA_OT', 'Nueva OT Agregada'), ('ELIMINAR_OT', 'OT Eliminada')], max_length=20)),
                ('orden_trabajo_id', models.IntegerField(blank=True, null=True)),
                ('item_ruta_id', models.IntegerField(blank=True, null=True)),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.programaproduccion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
