# Generated by Django 5.2.6 on 2025-09-10 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0019_itemruta_duracion_planificada_horas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_ots', models.IntegerField(default=0)),
                ('total_procesos', models.IntegerField(default=0)),
                ('avance_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produccion_planificada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_producido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('kilos_producidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ots_completadas', models.IntegerField(default=0)),
                ('ots_en_proceso', models.IntegerField(default=0)),
                ('ots_pendientes', models.IntegerField(default=0)),
                ('datos_ordenes', models.JSONField(default=dict, help_text='Datos detallados de todas las OTs del día')),
                ('metricas_adicionales', models.JSONField(default=dict, help_text='Métricas calculadas adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('importacion_realizada', models.BooleanField(default=False, help_text='Si se importaron avances externos')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='JobManagement.programaproduccion')),
            ],
            options={
                'verbose_name': 'Snapshot Diario',
                'verbose_name_plural': 'Snapshots Diarios',
                'ordering': ['-fecha'],
                'unique_together': {('programa', 'fecha')},
            },
        ),
    ]
