# Generated by Django 4.2.23 on 2025-08-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0016_ingresoproduccion'),
        ('Operator', '0001_initial'),
        ('Machine', '0002_alter_estadomaquina_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallasMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallas', to='JobManagement.maquina')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operator.operador')),
            ],
            options={
                'verbose_name': 'Falla de Máquina',
                'verbose_name_plural': 'Fallos de Máquinas',
                'ordering': ['-fecha'],
            },
        ),
    ]
